### YamlMime:ManagedReference
items:
- uid: Menu.Remix.ConfigContainer.Mode
  commentId: T:Menu.Remix.ConfigContainer.Mode
  id: ConfigContainer.Mode
  parent: Menu.Remix
  children:
  - Menu.Remix.ConfigContainer.Mode.ModConfig
  - Menu.Remix.ConfigContainer.Mode.ModSelect
  - Menu.Remix.ConfigContainer.Mode.ModView
  langs:
  - csharp
  - vb
  name: ConfigContainer.Mode
  nameWithType: ConfigContainer.Mode
  fullName: Menu.Remix.ConfigContainer.Mode
  type: Enum
  assemblies:
  - Assembly-CSharp
  namespace: Menu.Remix
  summary: >-
    <markup>
      <include item="SMCMissingTag">
        <parameter>summary</parameter>
        <parameter>T:Menu.Remix.ConfigContainer.Mode</parameter>
      </include>
    </markup>
  example: []
  syntax:
    content: public enum ConfigContainer.Mode
    content.vb: Public Enum ConfigContainer.Mode
- uid: Menu.Remix.ConfigContainer.Mode.ModSelect
  commentId: F:Menu.Remix.ConfigContainer.Mode.ModSelect
  id: ModSelect
  parent: Menu.Remix.ConfigContainer.Mode
  langs:
  - csharp
  - vb
  name: ModSelect
  nameWithType: ConfigContainer.Mode.ModSelect
  fullName: Menu.Remix.ConfigContainer.Mode.ModSelect
  type: Field
  assemblies:
  - Assembly-CSharp
  namespace: Menu.Remix
  syntax:
    content: ModSelect = 0
    return:
      type: Menu.Remix.ConfigContainer.Mode
- uid: Menu.Remix.ConfigContainer.Mode.ModView
  commentId: F:Menu.Remix.ConfigContainer.Mode.ModView
  id: ModView
  parent: Menu.Remix.ConfigContainer.Mode
  langs:
  - csharp
  - vb
  name: ModView
  nameWithType: ConfigContainer.Mode.ModView
  fullName: Menu.Remix.ConfigContainer.Mode.ModView
  type: Field
  assemblies:
  - Assembly-CSharp
  namespace: Menu.Remix
  syntax:
    content: ModView = 1
    return:
      type: Menu.Remix.ConfigContainer.Mode
- uid: Menu.Remix.ConfigContainer.Mode.ModConfig
  commentId: F:Menu.Remix.ConfigContainer.Mode.ModConfig
  id: ModConfig
  parent: Menu.Remix.ConfigContainer.Mode
  langs:
  - csharp
  - vb
  name: ModConfig
  nameWithType: ConfigContainer.Mode.ModConfig
  fullName: Menu.Remix.ConfigContainer.Mode.ModConfig
  type: Field
  assemblies:
  - Assembly-CSharp
  namespace: Menu.Remix
  syntax:
    content: ModConfig = 2
    return:
      type: Menu.Remix.ConfigContainer.Mode
references:
- uid: Menu.Remix
  commentId: N:Menu.Remix
  isExternal: true
  href: Menu.html
  name: Menu.Remix
  nameWithType: Menu.Remix
  fullName: Menu.Remix
  spec.csharp:
  - uid: Menu
    name: Menu
    isExternal: true
    href: Menu.html
  - name: .
  - uid: Menu.Remix
    name: Remix
    isExternal: true
    href: Menu.Remix.html
  spec.vb:
  - uid: Menu
    name: Menu
    isExternal: true
    href: Menu.html
  - name: .
  - uid: Menu.Remix
    name: Remix
    isExternal: true
    href: Menu.Remix.html
- uid: Menu.Remix.ConfigContainer.Mode
  commentId: T:Menu.Remix.ConfigContainer.Mode
  parent: Menu.Remix
  isExternal: true
  href: Menu.Remix.ConfigContainer.html
  name: ConfigContainer.Mode
  nameWithType: ConfigContainer.Mode
  fullName: Menu.Remix.ConfigContainer.Mode
  spec.csharp:
  - uid: Menu.Remix.ConfigContainer
    name: ConfigContainer
    isExternal: true
    href: Menu.Remix.ConfigContainer.html
  - name: .
  - uid: Menu.Remix.ConfigContainer.Mode
    name: Mode
    isExternal: true
    href: Menu.Remix.ConfigContainer.Mode.html
  spec.vb:
  - uid: Menu.Remix.ConfigContainer
    name: ConfigContainer
    isExternal: true
    href: Menu.Remix.ConfigContainer.html
  - name: .
  - uid: Menu.Remix.ConfigContainer.Mode
    name: Mode
    isExternal: true
    href: Menu.Remix.ConfigContainer.Mode.html
